//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testtProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favourite_moviee
    {
        public int user_id { get; set; }
        public int movie_id { get; set; }
        public Nullable<int> Is_Favourite { get; set; }
    
        public virtual Moviee Moviee { get; set; }
        public virtual Userr Userr { get; set; }
    }
}
