//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testtProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favourite_actorr
    {
        public int use_id { get; set; }
        public int actor_id { get; set; }
        public Nullable<int> IS_Favourie { get; set; }
    
        public virtual Actorr Actorr { get; set; }
        public virtual Userr Userr { get; set; }
    }
}
