//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testtProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moviee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Moviee()
        {
            this.favourite_moviee = new HashSet<favourite_moviee>();
            this.Like_or_dislike_moviee = new HashSet<Like_or_dislike_moviee>();
            this.Actorrs = new HashSet<Actorr>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string discription { get; set; }
        public string image { get; set; }
        public int Director { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favourite_moviee> favourite_moviee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like_or_dislike_moviee> Like_or_dislike_moviee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actorr> Actorrs { get; set; }
    }
}
