//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testtProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Userr()
        {
            this.favourite_actorr = new HashSet<favourite_actorr>();
            this.favourite_directorr = new HashSet<favourite_directorr>();
            this.favourite_moviee = new HashSet<favourite_moviee>();
            this.Like_or_dislike_moviee = new HashSet<Like_or_dislike_moviee>();
        }
    
        public int id { get; set; }
        public string First_name { get; set; }
        public string Last_Name { get; set; }
        public string profile_picture { get; set; }
        public string Email { get; set; }
        public string password { get; set; }
        public string confirmPass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favourite_actorr> favourite_actorr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favourite_directorr> favourite_directorr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favourite_moviee> favourite_moviee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like_or_dislike_moviee> Like_or_dislike_moviee { get; set; }
    }
}
